packages:
  - packages/apps/*
  - packages/canisters/*
  - packages/declarations
  - packages/libs/*
  - packages/services/*
  - packages/tests/*

onlyBuiltDependencies:
  - '@dfinity/pic'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild

overrides:
  braces@<2.3.1: '>=2.3.1'
  braces@<3.0.3: '>=3.0.3'
  esbuild@<=0.24.2: '>=0.25.0'
  micromatch@<4.0.8: '>=4.0.8'
